-- SmartLab AI - Auth Service MySQL Schema
-- Database: auth_db

CREATE DATABASE IF NOT EXISTS auth_db;
USE auth_db;

DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS FACULTY;
DROP TABLE IF EXISTS ADMINS;
DROP TABLE IF EXISTS student_profiles;
DROP TABLE IF EXISTS faculty_profiles;
DROP TABLE IF EXISTS admin_profiles;
DROP TABLE IF EXISTS OTP_RECORDS;
DROP TABLE IF EXISTS APP_USERS;

-- App Users (Parent / Credentials table)
CREATE TABLE APP_USERS (
    USER_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    EMAIL      VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255),
    ROLE       VARCHAR(20) NOT NULL,
    STATUS     VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    REG_NO     VARCHAR(50),
    FACULTY_ID VARCHAR(50),
    DOB        DATE
);

-- Students Profile (Child Table)
CREATE TABLE STUDENTS (
    STUDENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT NOT NULL,
    REG_NO     VARCHAR(50),
    DOB        DATE,
    CONSTRAINT FK_STUDENT_USER FOREIGN KEY (USER_ID) REFERENCES APP_USERS (USER_ID) ON DELETE CASCADE
);

-- Faculty Profile (Child Table)
CREATE TABLE FACULTY (
    FACULTY_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      BIGINT NOT NULL,
    FACULTY_CODE VARCHAR(50),
    DOB          DATE,
    CONSTRAINT FK_FACULTY_USER FOREIGN KEY (USER_ID) REFERENCES APP_USERS (USER_ID) ON DELETE CASCADE
);

-- Admins Profile (Child Table)
CREATE TABLE ADMINS (
    ADMIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID  BIGINT NOT NULL,
    CONSTRAINT FK_ADMIN_USER FOREIGN KEY (USER_ID) REFERENCES APP_USERS (USER_ID) ON DELETE CASCADE
);

-- OTP Records
CREATE TABLE OTP_RECORDS (
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL         VARCHAR(150) NOT NULL,
    OTP           VARCHAR(10) NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'ACTIVE',
    ATTEMPT_COUNT INT DEFAULT 0,
    CREATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_TIME   DATETIME NOT NULL,
    VERIFIED      BOOLEAN DEFAULT FALSE
);