const history = [
  {
    id: 1,
    report: "Student Report",
    generatedBy: "Admin",
    date: "05 Jul 2026",
    format: "PDF",
  },
  {
    id: 2,
    report: "Equipment Report",
    generatedBy: "Admin",
    date: "04 Jul 2026",
    format: "Excel",
  },
  {
    id: 3,
    report: "Booking Report",
    generatedBy: "Lab Coordinator",
    date: "03 Jul 2026",
    format: "PDF",
  },
  {
    id: 4,
    report: "Maintenance Report",
    generatedBy: "Admin",
    date: "02 Jul 2026",
    format: "Excel",
  },
];

const ReportHistory = () => {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden">

      <div className="px-6 py-5 border-b border-slate-800">

        <h2 className="text-2xl font-bold">

          Report History

        </h2>

      </div>

      <div className="overflow-x-auto">

        <table className="w-full">

          <thead className="bg-slate-800">

            <tr>

              <th className="px-5 py-4 text-left">
                Report
              </th>

              <th className="px-5 py-4 text-left">
                Generated By
              </th>

              <th className="px-5 py-4 text-left">
                Date
              </th>

              <th className="px-5 py-4 text-left">
                Format
              </th>

            </tr>

          </thead>

          <tbody>

            {history.map((item) => (

              <tr
                key={item.id}
                className="border-b border-slate-800 hover:bg-slate-800"
              >

                <td className="px-5 py-4">
                  {item.report}
                </td>

                <td className="px-5 py-4">
                  {item.generatedBy}
                </td>

                <td className="px-5 py-4">
                  {item.date}
                </td>

                <td className="px-5 py-4">

                  <span className="bg-orange-500/20 text-orange-400 px-3 py-1 rounded-full text-sm">

                    {item.format}

                  </span>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
};

export default ReportHistory;