-- SmartLab AI - Employee Service MySQL Schema
-- Database: smartlab

CREATE DATABASE IF NOT EXISTS smartlab;
USE smartlab;

-- Students
CREATE TABLE IF NOT EXISTS STUDENTS (
    STUDENT_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(150) NOT NULL UNIQUE,
    DEPARTMENT    VARCHAR(80) NOT NULL,
    YEAR          INT NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'Active',
    PHONE         VARCHAR(20)
);

-- Faculty
CREATE TABLE IF NOT EXISTS FACULTY (
    FACULTY_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(150) NOT NULL UNIQUE,
    DEPARTMENT    VARCHAR(80) NOT NULL,
    DESIGNATION   VARCHAR(50) NOT NULL,
    PHONE         VARCHAR(20)
);

-- Departments
CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    DEPARTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL UNIQUE
);

-- Laboratories
CREATE TABLE IF NOT EXISTS LABORATORIES (
    LAB_ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    LOCATION      VARCHAR(150),
    CONSTRAINT FK_LAB_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE CASCADE
);

-- Equipment
CREATE TABLE IF NOT EXISTS EQUIPMENTS (
    EQUIPMENT_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL,
    LAB_ID        BIGINT NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'Available',
    CONSTRAINT FK_EQUIP_LAB FOREIGN KEY (LAB_ID) REFERENCES LABORATORIES(LAB_ID) ON DELETE CASCADE
);

-- Bookings
CREATE TABLE IF NOT EXISTS BOOKINGS (
    BOOKING_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID    BIGINT NOT NULL,
    EQUIPMENT_ID  BIGINT NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'Pending',
    BOOKED_AT     DATETIME NOT NULL,
    PURPOSE       VARCHAR(255),
    TIME_SLOT     VARCHAR(100),
    DATE          VARCHAR(50),
    APPROVED_BY   BIGINT,
    CONSTRAINT FK_BOOK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    CONSTRAINT FK_BOOK_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS(EQUIPMENT_ID),
    CONSTRAINT FK_BOOK_FACULTY FOREIGN KEY (APPROVED_BY) REFERENCES FACULTY(FACULTY_ID)
);

-- Fault Reports
CREATE TABLE IF NOT EXISTS FAULT_REPORTS (
    FAULT_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID  BIGINT NOT NULL,
    REPORTED_BY   BIGINT NOT NULL,
    DESCRIPTION   VARCHAR(255) NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'Open',
    REPORTED_AT   DATETIME NOT NULL,
    CONSTRAINT FK_FAULT_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS(EQUIPMENT_ID),
    CONSTRAINT FK_FAULT_STUDENT FOREIGN KEY (REPORTED_BY) REFERENCES STUDENTS(STUDENT_ID)
);

-- Maintenance
CREATE TABLE IF NOT EXISTS MAINTENANCE (
    MAINTENANCE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID   BIGINT NOT NULL,
    SCHEDULED_AT   DATETIME NOT NULL,
    STATUS         VARCHAR(20) DEFAULT 'Scheduled',
    NOTES          VARCHAR(255),
    CONSTRAINT FK_MAINT_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS(EQUIPMENT_ID)
);
