-- SmartLab AI - SmartLab Service MySQL Schema
-- Database: smartlab

CREATE DATABASE IF NOT EXISTS smartlab;
USE smartlab;

DROP TABLE IF EXISTS NOTIFICATIONS;
DROP TABLE IF EXISTS MAINTENANCE;
DROP TABLE IF EXISTS FAULT_REPORTS;
DROP TABLE IF EXISTS BOOKINGS;
DROP TABLE IF EXISTS EQUIPMENT;
DROP TABLE IF EXISTS EQUIPMENTS;
DROP TABLE IF EXISTS LABORATORIES;
DROP TABLE IF EXISTS STUDENT_PROFILES;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS FACULTY_PROFILES;
DROP TABLE IF EXISTS FACULTY;
DROP TABLE IF EXISTS DEPARTMENTS;

-- Departments
CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(100) NOT NULL UNIQUE,
    CODE          VARCHAR(50) UNIQUE,
    HOD           VARCHAR(100),
    STATUS        VARCHAR(20) DEFAULT 'ACTIVE'
);

-- Student Profiles
CREATE TABLE STUDENT_PROFILES (
    STUDENT_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID       BIGINT NOT NULL UNIQUE,
    DEPARTMENT_ID BIGINT NOT NULL,
    REG_NO        VARCHAR(50) NOT NULL UNIQUE,
    YEAR          INT NOT NULL,
    SECTION       VARCHAR(10),
    NAME          VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(150) NOT NULL UNIQUE,
    STATUS        VARCHAR(20) DEFAULT 'Active',
    PHONE         VARCHAR(20),
    CONSTRAINT FK_STUDENT_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

-- Faculty Profiles
CREATE TABLE FACULTY_PROFILES (
    FACULTY_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID       BIGINT NOT NULL UNIQUE,
    DEPARTMENT_ID BIGINT NOT NULL,
    DESIGNATION   VARCHAR(50) NOT NULL,
    NAME          VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(150) NOT NULL UNIQUE,
    PHONE         VARCHAR(20),
    STATUS        VARCHAR(20) DEFAULT 'ACTIVE',
    LAB           VARCHAR(100),
    CONSTRAINT FK_FACULTY_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

-- Laboratories
CREATE TABLE LABORATORIES (
    LAB_ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_ID BIGINT NOT NULL,
    NAME          VARCHAR(100) NOT NULL,
    LOCATION      VARCHAR(150),
    CAPACITY      INT,
    STATUS        VARCHAR(20) DEFAULT 'Active',
    CONSTRAINT FK_LAB_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE CASCADE
);

-- Equipment (replaces EQUIPMENTS)
CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    LAB_ID        BIGINT NOT NULL,
    ASSET_ID      VARCHAR(50) UNIQUE,
    NAME          VARCHAR(100) NOT NULL,
    CATEGORY      VARCHAR(50),
    DESCRIPTION   VARCHAR(255),
    STATUS        VARCHAR(20) DEFAULT 'Available',
    PURCHASE_DATE DATE,
    IMAGE_URL     VARCHAR(255),
    CONSTRAINT FK_EQUIP_LAB FOREIGN KEY (LAB_ID) REFERENCES LABORATORIES(LAB_ID) ON DELETE CASCADE
);

-- Bookings
CREATE TABLE BOOKINGS (
    BOOKING_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID    BIGINT NOT NULL,
    EQUIPMENT_ID  BIGINT NOT NULL,
    BOOKING_DATE  DATE,
    START_TIME    VARCHAR(50),
    END_TIME      VARCHAR(50),
    STATUS        VARCHAR(20) DEFAULT 'Pending',
    PURPOSE       VARCHAR(255),
    BOOKED_AT     DATETIME NOT NULL,
    APPROVED_BY   BIGINT,
    CONSTRAINT FK_BOOK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_PROFILES(STUDENT_ID),
    CONSTRAINT FK_BOOK_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(EQUIPMENT_ID),
    CONSTRAINT FK_BOOK_FACULTY FOREIGN KEY (APPROVED_BY) REFERENCES FACULTY_PROFILES(FACULTY_ID)
);

-- Fault Reports
CREATE TABLE FAULT_REPORTS (
    FAULT_ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID        BIGINT NOT NULL,
    REPORTED_BY_USER_ID BIGINT NOT NULL,
    DESCRIPTION         VARCHAR(255) NOT NULL,
    STATUS              VARCHAR(20) DEFAULT 'Open',
    REPORTED_AT         DATETIME NOT NULL,
    RESOLVED_AT         DATETIME,
    CONSTRAINT FK_FAULT_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(EQUIPMENT_ID)
);

-- Maintenance
CREATE TABLE MAINTENANCE (
    MAINTENANCE_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID        BIGINT NOT NULL,
    ASSIGNED_TO_USER_ID BIGINT,
    DESCRIPTION         VARCHAR(255),
    STATUS              VARCHAR(20) DEFAULT 'Scheduled',
    SCHEDULED_DATE      DATE,
    COMPLETED_DATE      DATE,
    TYPE                VARCHAR(50) DEFAULT 'Preventive',
    CONSTRAINT FK_MAINT_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(EQUIPMENT_ID)
);

-- Notifications
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID         BIGINT NOT NULL,
    USER_ROLE       VARCHAR(20),
    TITLE           VARCHAR(100),
    MESSAGE         TEXT,
    TYPE            VARCHAR(50),
    IS_READ         BOOLEAN DEFAULT FALSE,
    CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP
);
